global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'metrics-aggregator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['metrics-aggregator:8080']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
  # - job_name: 'postgresql'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']